#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config focus_follows_mouse          autoraise
yabai -m config split_type                   auto
yabai -m config split_ratio                  5.0
yabai -m config window_zoom_persist          on
yabai -m config display_arrangement_order    defaulit
yabai -m config window_opacity               on
yabai -m config normal_window_opacity        0.0


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               4
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   0
yabai -m config external_bar                 all:38:30

# apps to not manage (ignore)
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^System Settings" manage=off 


# spacebar padding on top screen
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# This focuses the previous window if a window is not currently focused, such as when a floating window is minimized
# https://github.com/koekeishiya/yabai/issues/1212#issuecomment-1107854658
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier ctrl


echo "yabai configuration loaded.."
