#!/bin/bash

options=(
	style=square
	width=2.0
	hidpi=on
	blur_radius=0.0
	active_color=0x80FF0000  # Semi-transparent white
	inactive_color=0x80FF0000  # Semi-transparent white
)

borders "${options[@]}"

