#!/bin/bash

options=(
	style=square
	width=2.0
	hidpi=on
	blur_radius=0.0
	order=above
  active_color=0x80FF0000
  inactive_color="gradient(top_left=0x77E60012,bottom_right=0x11181818,top_right=0x77E60012,bottom_left=0x11181818)"
	background_color=0x00000000
)

borders "${options[@]}"



