#!/usr/bin/env sh

spacebar -m config position                    top
spacebar -m config display                     all
spacebar -m config height                      45
spacebar -m config title                       on
spacebar -m config spaces                      on
spacebar -m config clock                       on
spacebar -m config power                       on
spacebar -m config padding_left                15
spacebar -m config padding_right               15
spacebar -m config spacing_left                25
spacebar -m config spacing_right               15
spacebar -m config text_font                   "Menlo:Regular:12.0"
spacebar -m config icon_font                   "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color            0x10000000
spacebar -m config foreground_color            0xffb82525
spacebar -m config power_icon_color            0xfff5f0f0
spacebar -m config battery_icon_color          0xfff5f0f0
spacebar -m config dnd_icon_color              0xfff5f0f0
spacebar -m config clock_icon_color            0xfff5f0f0
spacebar -m config right_shell_icon_color      0xfff5f0f0
spacebar -m config power_icon_strip             
spacebar -m config space_icon                  •
spacebar -m config space_icon_color            0xfff5f0f0
spacebar -m config space_icon_color_secondary  0xffb82525
spacebar -m config space_icon_color_tertiary   0xffb82525
spacebar -m config space_icon_strip               
spacebar -m config spaces_for_all_displays     on
spacebar -m config clock_icon                  
spacebar -m config dnd_icon                    
spacebar -m config clock_format                "%m/%d/%y %I:%M"
spacebar -m config right_shell                 on
spacebar -m config right_shell_icon             
spacebar -m config right_shell_command         "source $HOME/.config/spacebar/combined.sh"
spacebar -m config left_shell                  on
spacebar -m config left_shell_command          "sh $HOME/.config/spacebar/spotify.sh"
spacebar -m config left_shell_icon             
spacebar -m config left_shell_icon_color       0xfff5f0f0
echo "spacebar configuration loaded.."
